// Copyright 2021-present StarRocks, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// S2 Serialization Compatibility Test
//
// This test verifies that binary GEO data encoded with S2 v0.9.0 can be
// correctly decoded after upgrading to a newer S2 version.
//
// The hex constants below were captured by running s2_compat_snapshot_gen
// with S2 v0.9.0 BEFORE the upgrade. They represent the exact bytes stored
// in tablet columns for existing GEO data.
//
// If any of these tests fail after an S2 upgrade, it means existing GEO data
// in production cannot be read correctly, and a migration strategy is needed.

#include "geo/geo_types.h"

#include <gtest/gtest.h>

#include <cstdint>
#include <memory>
#include <string>

#include "geo/wkt_parse.h"

namespace starrocks {

class S2SerializationCompatTest : public ::testing::Test {
protected:
    // Helper: convert hex string to binary
    static std::string hex_to_binary(const std::string& hex) {
        std::string binary;
        binary.reserve(hex.size() / 2);
        for (size_t i = 0; i + 1 < hex.size(); i += 2) {
            auto byte = static_cast<char>(std::stoi(hex.substr(i, 2), nullptr, 16));
            binary.push_back(byte);
        }
        return binary;
    }

    // Helper: encode a shape and return hex
    static std::string encode_to_hex(GeoShape* shape) {
        std::string buf;
        shape->encode_to(&buf);
        std::string hex;
        for (unsigned char c : buf) {
            char h[3];
            snprintf(h, sizeof(h), "%02x", c);
            hex.append(h);
        }
        return hex;
    }

    // ========================================================================
    // V0.9.0 HEX SNAPSHOTS
    //
    // Generated by running s2_compat_snapshot_gen with S2 v0.9.0.
    // TODO: Replace these placeholder values with actual captured hex after
    //       running the snapshot generator with the OLD S2 version.
    //
    // To generate: build and run with S2 v0.9.0:
    //   ./run-be-ut.sh --gtest_filter "S2CompatSnapshotGen.GenerateAllSnapshotsCompact"
    // ========================================================================

    // ST_Point(116.123, 63.546)
    // Format: [0x00][0x01][24 bytes raw S2Point = 3 doubles]
    // Note: GeoPoint uses raw memcpy, NOT S2 Encode/Decode, so this is
    //       version-independent (3 IEEE 754 doubles).
    static inline const std::string kV090PointHex =
            "PLACEHOLDER_POINT_RUN_SNAPSHOT_GEN";

    // LINESTRING (30 10, 10 30, 40 40)
    // Format: [0x00][0x02][S2Polyline::Encode version=1 data]
    static inline const std::string kV090LineHex =
            "PLACEHOLDER_LINE_RUN_SNAPSHOT_GEN";

    // POLYGON ((10 10, 50 10, 50 50, 10 50, 10 10))
    // Format: [0x00][0x03][S2Polygon::Encode version=1 data]
    static inline const std::string kV090PolygonHex =
            "PLACEHOLDER_POLYGON_RUN_SNAPSHOT_GEN";

    // POLYGON ((10 10, 50 10, 50 50, 10 50, 10 10), (20 20, 40 20, 40 40, 20 40, 20 20))
    // Format: [0x00][0x03][S2Polygon::Encode with 2 loops]
    static inline const std::string kV090PolygonHoleHex =
            "PLACEHOLDER_POLYGON_HOLE_RUN_SNAPSHOT_GEN";

    // CIRCLE ((110.123 64), 1000)
    // Format: [0x00][0x07][S2Cap::Encode = 32 bytes, no version marker]
    static inline const std::string kV090CircleHex =
            "PLACEHOLDER_CIRCLE_RUN_SNAPSHOT_GEN";

    // Helper: check if snapshots have been generated
    static bool snapshots_available() {
        return kV090PointHex.find("PLACEHOLDER") == std::string::npos;
    }
};

// =============================================================================
// Test 1: v0.9.0 encoded Point → current version decode
// =============================================================================
TEST_F(S2SerializationCompatTest, DecodeV090Point) {
    if (!snapshots_available()) {
        GTEST_SKIP() << "Snapshots not yet generated. Run S2CompatSnapshotGen first.";
    }

    auto bin = hex_to_binary(kV090PointHex);
    ASSERT_GE(bin.size(), 2u) << "Point binary too small";
    ASSERT_EQ(0x00, static_cast<uint8_t>(bin[0])) << "Reserved byte mismatch";
    ASSERT_EQ(0x01, static_cast<uint8_t>(bin[1])) << "Type byte should be GEO_SHAPE_POINT(1)";

    std::unique_ptr<GeoShape> shape(GeoShape::from_encoded(bin.data(), bin.size()));
    ASSERT_NE(nullptr, shape) << "Failed to decode v0.9.0 Point";
    ASSERT_EQ(GEO_SHAPE_POINT, shape->type());
    ASSERT_STREQ("POINT (116.123 63.546)", shape->as_wkt().c_str());

    // Verify coordinate precision
    auto* point = static_cast<GeoPoint*>(shape.get());
    EXPECT_NEAR(116.123, point->x(), 1e-6);
    EXPECT_NEAR(63.546, point->y(), 1e-6);
}

// =============================================================================
// Test 2: v0.9.0 encoded LineString → current version decode
// =============================================================================
TEST_F(S2SerializationCompatTest, DecodeV090LineString) {
    if (!snapshots_available()) {
        GTEST_SKIP() << "Snapshots not yet generated.";
    }

    auto bin = hex_to_binary(kV090LineHex);
    ASSERT_GE(bin.size(), 2u);
    ASSERT_EQ(0x00, static_cast<uint8_t>(bin[0]));
    ASSERT_EQ(0x02, static_cast<uint8_t>(bin[1])) << "Type byte should be GEO_SHAPE_LINE_STRING(2)";

    std::unique_ptr<GeoShape> shape(GeoShape::from_encoded(bin.data(), bin.size()));
    ASSERT_NE(nullptr, shape) << "Failed to decode v0.9.0 LineString";
    ASSERT_EQ(GEO_SHAPE_LINE_STRING, shape->type());
    ASSERT_STREQ("LINESTRING (30 10, 10 30, 40 40)", shape->as_wkt().c_str());
}

// =============================================================================
// Test 3: v0.9.0 encoded Polygon → current version decode + spatial ops
// =============================================================================
TEST_F(S2SerializationCompatTest, DecodeV090Polygon) {
    if (!snapshots_available()) {
        GTEST_SKIP() << "Snapshots not yet generated.";
    }

    auto bin = hex_to_binary(kV090PolygonHex);
    ASSERT_GE(bin.size(), 2u);
    ASSERT_EQ(0x00, static_cast<uint8_t>(bin[0]));
    ASSERT_EQ(0x03, static_cast<uint8_t>(bin[1])) << "Type byte should be GEO_SHAPE_POLYGON(3)";

    std::unique_ptr<GeoShape> shape(GeoShape::from_encoded(bin.data(), bin.size()));
    ASSERT_NE(nullptr, shape) << "Failed to decode v0.9.0 Polygon";
    ASSERT_EQ(GEO_SHAPE_POLYGON, shape->type());

    // Verify spatial operations still work correctly
    GeoPoint inside, outside;
    inside.from_coord(20, 20);
    outside.from_coord(5, 5);
    EXPECT_TRUE(shape->contains(&inside)) << "Polygon should contain point (20,20)";
    EXPECT_FALSE(shape->contains(&outside)) << "Polygon should not contain point (5,5)";
}

// =============================================================================
// Test 4: v0.9.0 encoded Polygon with hole → current version decode
// =============================================================================
TEST_F(S2SerializationCompatTest, DecodeV090PolygonWithHole) {
    if (!snapshots_available()) {
        GTEST_SKIP() << "Snapshots not yet generated.";
    }

    auto bin = hex_to_binary(kV090PolygonHoleHex);
    std::unique_ptr<GeoShape> shape(GeoShape::from_encoded(bin.data(), bin.size()));
    ASSERT_NE(nullptr, shape) << "Failed to decode v0.9.0 Polygon with hole";
    ASSERT_EQ(GEO_SHAPE_POLYGON, shape->type());

    // Point in outer ring but outside hole → should be contained
    GeoPoint in_ring;
    in_ring.from_coord(15, 15);
    EXPECT_TRUE(shape->contains(&in_ring)) << "Point in ring should be contained";

    // Point inside the hole → should NOT be contained
    GeoPoint in_hole;
    in_hole.from_coord(25, 25);
    EXPECT_FALSE(shape->contains(&in_hole)) << "Point in hole should not be contained";

    // Point outside polygon entirely → should NOT be contained
    GeoPoint outside;
    outside.from_coord(5, 5);
    EXPECT_FALSE(shape->contains(&outside)) << "Point outside should not be contained";
}

// =============================================================================
// Test 5: v0.9.0 encoded Circle → current version decode
// =============================================================================
TEST_F(S2SerializationCompatTest, DecodeV090Circle) {
    if (!snapshots_available()) {
        GTEST_SKIP() << "Snapshots not yet generated.";
    }

    auto bin = hex_to_binary(kV090CircleHex);
    ASSERT_GE(bin.size(), 2u);
    ASSERT_EQ(0x00, static_cast<uint8_t>(bin[0]));
    ASSERT_EQ(0x07, static_cast<uint8_t>(bin[1])) << "Type byte should be GEO_SHAPE_CIRCLE(7)";

    std::unique_ptr<GeoShape> shape(GeoShape::from_encoded(bin.data(), bin.size()));
    ASSERT_NE(nullptr, shape) << "Failed to decode v0.9.0 Circle";
    ASSERT_EQ(GEO_SHAPE_CIRCLE, shape->type());
    ASSERT_STREQ("CIRCLE ((110.123 64), 1000)", shape->as_wkt().c_str());
}

// =============================================================================
// Test 6: Round-trip — decode v0.9.0 → re-encode with current → decode again
// =============================================================================
TEST_F(S2SerializationCompatTest, RoundTripReEncode) {
    if (!snapshots_available()) {
        GTEST_SKIP() << "Snapshots not yet generated.";
    }

    struct TestCase {
        const std::string& hex;
        GeoShapeType expected_type;
        const char* name;
    };

    TestCase cases[] = {
            {kV090PointHex, GEO_SHAPE_POINT, "Point"},
            {kV090LineHex, GEO_SHAPE_LINE_STRING, "LineString"},
            {kV090PolygonHex, GEO_SHAPE_POLYGON, "Polygon"},
            {kV090CircleHex, GEO_SHAPE_CIRCLE, "Circle"},
    };

    for (const auto& tc : cases) {
        SCOPED_TRACE(tc.name);
        auto bin = hex_to_binary(tc.hex);

        // Decode from v0.9.0 binary
        std::unique_ptr<GeoShape> shape1(GeoShape::from_encoded(bin.data(), bin.size()));
        ASSERT_NE(nullptr, shape1) << "Decode failed for " << tc.name;
        ASSERT_EQ(tc.expected_type, shape1->type());
        auto wkt1 = shape1->as_wkt();

        // Re-encode with current version
        std::string re_encoded;
        shape1->encode_to(&re_encoded);

        // Decode again
        std::unique_ptr<GeoShape> shape2(GeoShape::from_encoded(re_encoded.data(), re_encoded.size()));
        ASSERT_NE(nullptr, shape2) << "Re-decode failed for " << tc.name;
        ASSERT_EQ(tc.expected_type, shape2->type());

        // WKT should match
        ASSERT_STREQ(wkt1.c_str(), shape2->as_wkt().c_str())
                << "WKT mismatch after round-trip for " << tc.name;
    }
}

// =============================================================================
// Test 7: Current version encode → decode (smoke test for new version)
// =============================================================================
TEST_F(S2SerializationCompatTest, CurrentVersionRoundTrip) {
    // Point
    {
        GeoPoint point;
        point.from_coord(116.123, 63.546);
        std::string buf;
        point.encode_to(&buf);
        std::unique_ptr<GeoShape> decoded(GeoShape::from_encoded(buf.data(), buf.size()));
        ASSERT_NE(nullptr, decoded);
        ASSERT_STREQ("POINT (116.123 63.546)", decoded->as_wkt().c_str());
    }

    // LineString
    {
        const char* wkt = "LINESTRING (30 10, 10 30, 40 40)";
        GeoParseStatus status;
        std::unique_ptr<GeoShape> shape(GeoShape::from_wkt(wkt, strlen(wkt), &status));
        ASSERT_EQ(GEO_PARSE_OK, status);
        std::string buf;
        shape->encode_to(&buf);
        std::unique_ptr<GeoShape> decoded(GeoShape::from_encoded(buf.data(), buf.size()));
        ASSERT_NE(nullptr, decoded);
        ASSERT_STREQ(wkt, decoded->as_wkt().c_str());
    }

    // Polygon
    {
        const char* wkt = "POLYGON ((10 10, 50 10, 50 50, 10 50, 10 10))";
        GeoParseStatus status;
        std::unique_ptr<GeoShape> shape(GeoShape::from_wkt(wkt, strlen(wkt), &status));
        ASSERT_EQ(GEO_PARSE_OK, status);
        std::string buf;
        shape->encode_to(&buf);
        std::unique_ptr<GeoShape> decoded(GeoShape::from_encoded(buf.data(), buf.size()));
        ASSERT_NE(nullptr, decoded);
        ASSERT_EQ(GEO_SHAPE_POLYGON, decoded->type());

        GeoPoint inside;
        inside.from_coord(20, 20);
        ASSERT_TRUE(decoded->contains(&inside));
    }

    // Circle
    {
        GeoCircle circle;
        circle.init(110.123, 64, 1000);
        std::string buf;
        circle.encode_to(&buf);
        std::unique_ptr<GeoShape> decoded(GeoShape::from_encoded(buf.data(), buf.size()));
        ASSERT_NE(nullptr, decoded);
        ASSERT_STREQ("CIRCLE ((110.123 64), 1000)", decoded->as_wkt().c_str());
    }
}

// =============================================================================
// Test 8: Binary format sanity checks (version-independent)
// =============================================================================
TEST_F(S2SerializationCompatTest, BinaryFormatSanity) {
    // Verify the 2-byte header format: [0x00 reserved][type byte]
    {
        GeoPoint point;
        point.from_coord(0, 0);
        std::string buf;
        point.encode_to(&buf);
        ASSERT_EQ(26u, buf.size()) << "Point should be 2-byte header + 24-byte S2Point";
        ASSERT_EQ(0x00, static_cast<uint8_t>(buf[0])) << "Reserved byte should be 0x00";
        ASSERT_EQ(0x01, static_cast<uint8_t>(buf[1])) << "Type byte for Point should be 1";
    }

    // Circle: 2-byte header + 32-byte S2Cap = 34 bytes
    {
        GeoCircle circle;
        circle.init(0, 0, 100);
        std::string buf;
        circle.encode_to(&buf);
        ASSERT_EQ(34u, buf.size()) << "Circle should be 2-byte header + 32-byte S2Cap";
        ASSERT_EQ(0x00, static_cast<uint8_t>(buf[0]));
        ASSERT_EQ(0x07, static_cast<uint8_t>(buf[1])) << "Type byte for Circle should be 7";
    }

    // Invalid data should return nullptr
    {
        // Empty
        ASSERT_EQ(nullptr, GeoShape::from_encoded("", 0));
        // Too short
        ASSERT_EQ(nullptr, GeoShape::from_encoded("\x00", 1));
        // Wrong reserved byte
        ASSERT_EQ(nullptr, GeoShape::from_encoded("\x01\x01", 2));
        // Unknown type
        ASSERT_EQ(nullptr, GeoShape::from_encoded("\x00\xFF", 2));
    }
}

} // namespace starrocks
